### ISSUE TITLE
Figure out why we need to submit manual conda-forge pinning migrations

### ISSUE THREAD

**Issue by akrherz** [conda-forge/geotiff-feedstock#77]
### Comment:

As with https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/7193 , we needed to submit a manual migration for geotiff.  Something must be messed up somewhere, so am opening an issue to figure out why! :)

**Comment by akrherz** [comment]
My initial guess is that we have `x.x` instead of `x.x.x`
```yaml
build:
  number: 1
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=libgeotiff
    - {{ pin_subpackage('geotiff', max_pin='x.x') }}
```
and conda-forge-pining has

```yaml
geotiff:
  - 1.7.3
```
